/**
 * @fileoverview High-performance enterprise search execution engine for the WG UI Platform.
 * Evaluates Abstract Syntax Trees (AST) produced by SearchParser against a local SearchIndexer instance.
 * Optimized for local in-memory dataset evaluations with zero external dependencies.
 */

/**
 * @typedef {string|number} DocumentId
 */

/**
 * @typedef {Object} ASTNode
 * @property {string} type - Node classification identifier ('TERM', 'PHRASE', 'FIELD', 'COMPARISON', 'LOGICAL', 'NOT', 'GROUP')
 * @property {string} [value] - Target value criteria
 * @property {string} [field] - Target property field schema key matches
 * @property {string} [operator] - Relational comparison assignment operator ('>', '>=', '<', '<=', '=')
 * @property {ASTNode} [left] - Left operand node branch context for logical pairings
 * @property {ASTNode} [right] - Right operand node branch context for logical pairings
 * @property {ASTNode} [operand] - Target leaf wrapper expression under negation evaluation paths
 */

/**
 * @typedef {Object} ExecutorStatistics
 * @property {number} executionTime - Measured operations execution duration in milliseconds.
 * @property {number} matchedCount - Total quantity of matching document profiles located.
 * @property {number} checkedTokens - Cumulative counter tracking total semantic lookup evaluations processed.
 */

/**
 * @typedef {Object} ExecutionResult
 * @property {Set<DocumentId>} matchedIds - Unique identifiers specifying matching elements.
 * @property {Object[]} matchedDocuments - Array of matching document object payloads.
 * @property {ExecutorStatistics} statistics - Operational runtime metadata details.
 */

/**
 * Enterprise-grade local search query execution engine.
 * Computes complex boolean compound queries against local indexing tables using set theory mechanics.
 */
export default class SearchExecutor {
  /** @type {Object|null} */
  #activeIndex;

  /** @type {number} */
  #checkedTokens;

  /**
   * Initializes a new instance of the SearchExecutor with pristine tracking variables.
   */
  constructor() {
    this.#activeIndex = null;
    this.#checkedTokens = 0;
  }

  /**
   * Processes a structured query AST blueprint layout across an active data index instance.
   * Defensively manages internal exceptions to guarantee clean, zero-throw runtime execution paths.
   *
   * @param {Object} index - Active SearchIndexer instance containing data records.
   * @param {Object} parsedQuery - Structurally sound return value generated by SearchParser.parse().
   * @returns {ExecutionResult} Consolidated standardized local search matches report.
   */
  execute(index, parsedQuery) {
    const startTime = performance.now();
    this.clear();

    // Defensive Constraint Validations
    if (!index || typeof index.getDocuments !== 'function' || typeof index.getTokenMatches !== 'function') {
      return this.#generateEmptyResult(startTime);
    }
    if (!parsedQuery || !parsedQuery.ast || typeof parsedQuery.ast !== 'object') {
      return this.#generateEmptyResult(startTime);
    }

    this.#activeIndex = index;

    let matchedIds;
    try {
      matchedIds = this.executeNode(parsedQuery.ast);
    } catch (error) {
      // Graceful structural recovery protection configuration context path
      matchedIds = new Set();
    }

    const matchedDocuments = this.getDocuments(matchedIds);
    const endTime = performance.now();

    const result = {
      matchedIds: matchedIds,
      matchedDocuments: matchedDocuments,
      statistics: {
        executionTime: endTime - startTime,
        matchedCount: matchedIds.size,
        checkedTokens: this.#checkedTokens
      }
    };

    // this.clear();
    return result;
  }

  /**
   * Recursive dispatcher function navigating structural layout types to execute matching logic.
   *
   * @param {ASTNode} node - Core tree configuration context block element under evaluation.
   * @returns {Set<DocumentId>} Calculated unique matching identity elements group keys.
   */
  executeNode(node) {
    if (!node || !node.type) {
      return new Set();
    }

    switch (node.type) {
      case 'TERM':
        return this.executeTerm(node);
      case 'PHRASE':
        return this.executePhrase(node);
      case 'FIELD':
        return this.executeField(node);
      case 'COMPARISON':
        return this.executeComparison(node);
      case 'LOGICAL':
        return this.executeLogical(node);
      case 'NOT':
        return this.executeNot(node);
      case 'GROUP':
        return this.executeGroup(node);
      default:
        return new Set();
    }
  }

  /**
   * Evaluates standard independent text search expression matches across inverted indexes.
   *
   * @param {ASTNode} node - Target query leaf element configuration metrics details.
   * @returns {Set<DocumentId>} Identified matching record keys collection set.
   */
  executeTerm(node) {
    if (!node.value) {
      return new Set();
    }
    this.#checkedTokens++;
    return this.#activeIndex.getTokenMatches(node.value);
  }

  /**
   * Computes precise phrase pattern checks utilizing combined spatial candidate set tracking strategies.
   *
   * @param {ASTNode} node - Structural target token constraints data structure.
   * @returns {Set<DocumentId>} Verified matching group key references.
   */
  executePhrase(node) {
    if (!node.value) {
      return new Set();
    }

    this.#checkedTokens++;
    const targetPhrase = String(node.value).toLowerCase().trim();
    const phraseWords = targetPhrase.split(/\s+/).filter(Boolean);

    if (phraseWords.length === 0) {
      return new Set();
    }

    // Optimization: Intersect matched document sets for all individual words to build candidates
    let candidateIds = null;
    const wordCount = phraseWords.length;

    for (let i = 0; i < wordCount; i++) {
      const wordMatches = this.#activeIndex.getTokenMatches(phraseWords[i]);
      if (candidateIds === null) {
        candidateIds = new Set(wordMatches);
      } else {
        candidateIds = this.intersection(candidateIds, wordMatches);
      }

      if (candidateIds.size === 0) {
        return new Set();
      }
    }

    // Verify candidates using string text inclusion matching parameters
    const confirmedIds = new Set();
    for (const docId of candidateIds) {
      const doc = this.#activeIndex.getDocument(docId);
      if (!doc || !doc.fields) {
        continue;
      }

      const fieldsKeys = Object.keys(doc.fields);
      const fieldsCount = fieldsKeys.length;
      let phraseIsMatched = false;

      for (let j = 0; j < fieldsCount; j++) {
        const val = doc.fields[fieldsKeys[j]];
        const contentString = Array.isArray(val) ? val.join(' ') : String(val || '');

        if (contentString.toLowerCase().includes(targetPhrase)) {
          phraseIsMatched = true;
          break;
        }
      }

      if (phraseIsMatched) {
        confirmedIds.add(docId);
      }
    }

    return confirmedIds;
  }

  /**
   * Targets token search evaluations scoped explicitly against isolated data classification properties.
   *
   * @param {ASTNode} node - Operational directives config metrics map parameters block.
   * @returns {Set<DocumentId>} Document mapping identities set.
   */
  executeField(node) {
    if (!node.field || !node.value) {
      return new Set();
    }
    this.#checkedTokens++;
    return this.#activeIndex.getFieldMatches(node.field, node.value);
  }

  /**
   * Evaluates custom logical comparison conditions matching boundaries across targeted document criteria metadata.
   *
   * @param {ASTNode} node - Target relational rule evaluation structural directives node block.
   * @returns {Set<DocumentId>} Calculated unique structural matches values collections.
   */
  executeComparison(node) {
    if (!node.field || !node.operator || node.value === undefined) {
      return new Set();
    }

    this.#checkedTokens++;
    const matchedIds = new Set();
    const allDocs = this.#activeIndex.getDocuments();
    const totalDocsCount = allDocs.length;

    for (let i = 0; i < totalDocsCount; i++) {
      const doc = allDocs[i];
      if (!doc || !doc.fields) {
        continue;
      }

      const rawVal = doc.fields[node.field];
      if (rawVal === undefined || rawVal === null) {
        continue;
      }

      // Handle structural evaluations across plain string values or array configurations cleanly
      if (Array.isArray(rawVal)) {
        const arrayLength = rawVal.length;
        for (let k = 0; k < arrayLength; k++) {
          if (this.#evaluateComparison(rawVal[k], node.operator, node.value)) {
            matchedIds.add(doc.id);
            break;
          }
        }
      } else {
        if (this.#evaluateComparison(rawVal, node.operator, node.value)) {
          matchedIds.add(doc.id);
        }
      }
    }

    return matchedIds;
  }

  /**
   * Performs set algebra configurations managing Boolean intersection (AND) and union (OR) processing blocks.
   *
   * @param {ASTNode} node - Compound criteria logical linkage node layout map.
   * @returns {Set<DocumentId>} Computed result metrics matrix block details.
   */
  executeLogical(node) {
    const leftSet = this.executeNode(node.left);
    
    // Fast-path optimization for logical AND operations (short-circuiting evaluation on empty conditions)
    if (node.operator === 'AND' && leftSet.size === 0) {
      return new Set();
    }

    const rightSet = this.executeNode(node.right);

    if (node.operator === 'AND') {
      return this.intersection(leftSet, rightSet);
    } else if (node.operator === 'OR') {
      return this.union(leftSet, rightSet);
    }

    return new Set();
  }

  /**
   * Implements relative inversion metrics (Logical Set Difference logic configuration routines).
   *
   * @param {ASTNode} node - Sub-tree negated argument parameter structural definitions map object.
   * @returns {Set<DocumentId>} Set containing non-excluded elements.
   */
  executeNot(node) {
    const exclusionSet = this.executeNode(node.operand);
    const allDocs = this.#activeIndex.getDocuments();
    const totalDocsCount = allDocs.length;
    const baseUniverseSet = new Set();

    for (let i = 0; i < totalDocsCount; i++) {
      const doc = allDocs[i];
      if (doc && doc.id !== undefined && doc.id !== null) {
        baseUniverseSet.add(doc.id);
      }
    }

    return this.difference(baseUniverseSet, exclusionSet);
  }

  /**
   * Resolves execution metrics paths contained explicitly inside protected bracket parameters groups.
   *
   * @param {ASTNode} node - Parenthetical context mapping details layout structure data blocks.
   * @returns {Set<DocumentId>} The inner calculated matches array metrics.
   */
  executeGroup(node) {
    return this.executeNode(node.operand);
  }

  /**
   * Merges two discrete unique data sets together into a unified collection matrix pool.
   *
   * @param {Set<DocumentId>} setA - Core target dataset structure array elements.
   * @param {Set<DocumentId>} setB - Companion structural additions records matching keys.
   * @returns {Set<DocumentId>} Combined Set instance profile layout data model structure.
   */
  union(setA, setB) {
    if (!setA || setA.size === 0) {
      return this.#cloneSet(setB);
    }
    if (!setB || setB.size === 0) {
      return this.#cloneSet(setA);
    }

    const result = new Set(setA);
    for (const item of setB) {
      result.add(item);
    }
    return result;
  }

  /**
   * Computes the mathematical intersection of two sets.
   * Implements high-performance fast-path scanning across the smaller collection subset.
   *
   * @param {Set<DocumentId>} setA - Context matrix comparison baseline values dataset structural group.
   * @param {Set<DocumentId>} setB - Target configuration values criteria reference block constraints.
   * @returns {Set<DocumentId>} Set listing only matching criteria mutual structural intersections elements.
   */
  intersection(setA, setB) {
    const result = new Set();
    if (!setA || !setB || setA.size === 0 || setB.size === 0) {
      return result;
    }

    const [smaller, larger] = setA.size < setB.size ? [setA, setB] : [setB, setA];
    for (const item of smaller) {
      if (larger.has(item)) {
        result.add(item);
      }
    }
    return result;
  }

  /**
   * Subtracts elements inside collection B out from core container structure collection space A.
   *
   * @param {Set<DocumentId>} setA - Baseline original source context universe collection properties.
   * @param {Set<DocumentId>} setB - Target exclusions constraints metadata array map fields items listings.
   * @returns {Set<DocumentId>} Trimmed clean output values object matrix configuration elements group.
   */
  difference(setA, setB) {
    if (!setA || setA.size === 0) {
      return new Set();
    }
    if (!setB || setB.size === 0) {
      return this.#cloneSet(setA);
    }

    const result = new Set(setA);
    for (const item of setB) {
      result.delete(item);
    }
    return result;
  }

  /**
   * Hydrates flat record lists by transforming target id sets into absolute document payloads.
   *
   * @param {Set<DocumentId>} ids - Source containing reference primary key identifier flags.
   * @returns {Object[]} Sequential array structure listing retrieved matching records structures configurations.
   */
  getDocuments(ids) {
    const documents = [];
    if (!ids || ids.size === 0 || !this.#activeIndex) {
      return documents;
    }

    for (const id of ids) {
      const doc = this.#activeIndex.getDocument(id);
      if (doc) {
        documents.push(doc);
      }
    }
    return documents;
  }

  /**
   * Cleans internal registers to wipe out trace references and facilitate clear memory management.
   *
   * @returns {void}
   */
  clear() {
    this.#activeIndex = null;
    this.#checkedTokens = 0;
  }

  /**
   * Internal routine running variable evaluations to resolve comparative mathematical relational bounds.
   *
   * @param {*} docValue - The actual key data field property value found inside record text profiles context.
   * @param {string} operator - Math criteria indicator operator symbols text.
   * @param {*} targetValue - Normalized boundary matching criteria standard assignment parameters value.
   * @returns {boolean} True if structural mathematical arguments evaluate as true.
   */
  #evaluateComparison(docValue, operator, targetValue) {
    let normalizedDocVal = docValue;
    let normalizedTargetVal = targetValue;

    // Automate logical numerical data conversions if checking metrics match digit syntax parameters
    if (typeof targetValue === 'number') {
      normalizedDocVal = Number(docValue);
      if (isNaN(normalizedDocVal)) {
        normalizedDocVal = String(docValue).toLowerCase();
        normalizedTargetVal = String(targetValue).toLowerCase();
      }
    } else {
      normalizedDocVal = String(docValue).toLowerCase();
      normalizedTargetVal = String(targetValue).toLowerCase();
    }

    switch (operator) {
      case '>':
        return normalizedDocVal > normalizedTargetVal;
      case '>=':
        return normalizedDocVal >= normalizedTargetVal;
      case '<':
        return normalizedDocVal < normalizedTargetVal;
      case '<=':
        return normalizedDocVal <= normalizedTargetVal;
      case '=':
        return normalizedDocVal === normalizedTargetVal;
      default:
        return false;
    }
  }

  /**
   * Safe data conversion utility parsing arbitrary iterable contexts down into structured Set wrappers.
   *
   * @param {*} iterable - Source element object collections structure configurations reference parameter.
   * @returns {Set<*>} A clean native JavaScript Set instance framework structural context.
   */
  #toSet(iterable) {
    if (!iterable) {
      return new Set();
    }
    return new Set(iterable);
  }

  /**
   * Generates a protected independent memory space copy duplication context from target sets structures.
   *
   * @param {Set<*>} set - Target data reference template configurations elements set mapping context.
   * @returns {Set<*>} Independent duplicate copy context instance layout structure details map.
   */
  #cloneSet(set) {
    if (!set) {
      return new Set();
    }
    return new Set(set);
  }

  /**
   * Helper utility establishing empty result template objects for structural exception exit recovery strategies.
   *
   * @param {number} startTime - Precise origin time checkpoint recorded in milliseconds.
   * @returns {ExecutionResult} Pristine empty initialized search operations response wrapper context layout structure.
   */
  #generateEmptyResult(startTime) {
    return {
      matchedIds: new Set(),
      matchedDocuments: [],
      statistics: {
        executionTime: performance.now() - startTime,
        matchedCount: 0,
        checkedTokens: 0
      }
    };
  }
}